### ISSUE TITLE
Destroy Event?

### ISSUE THREAD

**Issue by bradleyDouglas** [Elkfox/Ajaxinate#11]
I'm currently working on a theme and the customer would like to set the pagination to 24, but give the user a 'View All' option. An onClick event works great for initializing Ajaxify. However, if the user wants to switch back to pagination there's no way (that I can see) to destroy Ajaxify. 

Any thoughts on how to implement something like this?

Thanks!

**Comment by ButsAndCats** [comment]
That's a good question...
Haven't need to use that yet so I'm not sure how to go about doing that as of yet. Will have to think on it.

I'm the mean time I would advise on just creating two templates, one which initialises ajaxify and one that does not.

**Comment by bradleyDouglas** [comment]
Thanks for the response. I did end up just creating two templates. Works great.

**Comment by ButsAndCats** [comment]
Will leave this issue open because this is something that could be added.

**Comment by Cam** [comment]
Good call I think. A destroy option is a noble inclusion.

**Comment by ButsAndCats** [comment]
Added in 2.0.4 3d8f5be
