### ISSUE TITLE
ajaxify is not defined when using with new Slate

### ISSUE THREAD

**Issue by marioloncarek** [Elkfox/Ajaxinate#18]
Hello, 
great plugin, i used it before. Now i want to implement it in new Slate which uses webpack. I get this error:

```
./layout/theme.liquid
Module build failed: ../assets/scripts/ajaxify.min.js:4
ajaxify = function ajaxify(e) {
        ^

ReferenceError: ajaxify is not defined
```

Could you help?

**Comment by marioloncarek** [comment]
managed to fix it just by declaring ajaxify as ` let variable`

**Comment by marioloncarek** [comment]
Yes im using es6 with babel, i will then use `const` . Thanks for help!

**Comment by ButsAndCats** [comment]
I am actually just re-writing this plugin so you may like to use the new version. I will let you know when it is up.

**Comment by marioloncarek** [comment]
please do, will try it immediately. thanks for your great work!

**Comment by ButsAndCats** [comment]
Okay, it's up now. There is some new documentation too. Your HTML structure might need to change
