### ISSUE TITLE
I am facing very slow product loading. Can someone suggest me how to increase the loading speed of  new products.

### ISSUE THREAD

**Issue by Arsalan16723** [Elkfox/Ajaxinate#23]

**Comment by Cam** [comment]
@Arsalan16723 I'd recommend making sure your product images aren't too large, that you aren't trying to load too many products at once (ie keep pagination too something sensible), and that you are using optimised image loading techniques (like lazyloading).

Ajaxinate just loads the next pages contents, so fetching those products is pretty much the same process as loading the next page. So if loading your subsequent pages is a little slow, so will loading more products with Ajaxinate.
