### ISSUE TITLE
Endless Scroll/Click not working on Edge

### ISSUE THREAD

**Issue by ArthurSCD** [Elkfox/Ajaxinate#24]
Hello,

I'm trying to figure out the reason I can't get endless scroll to work on Edge. 
https://2og9j9nshet8mw3y-7018969.shopifypreview.com/collections/jewelry-archive

It works fine in Chrome and Firefox on Windows.
However I can get an error to pop in console on Edge -
`InvalidAccessError`
`ajaxinate.min.js (122,3)`
Which is 
```  this.request.responseType = 'document';```

However I can see https://ajaxify.myshopify.com/collections/all is working fine in the same Edge. It's really quite perplexing. There doesn't seem to be any discernible difference. 

Any advice would be appreciated.

**Comment by Cam** [comment]
@ArthurSCD looking at that page with the inspector, I can see that there are a lot of errors firing on the page. That's probably what is stopping Ajaxinate from being able to fire properly in some situations.

Check out the error at line 8299 of the rendered code in your console.

It looks like this is an issue with other code in that theme, and not with Ajaxinate, so I'll close this out for now.
