### ISSUE TITLE
Endless Click Breaks Jquery Slider

### ISSUE THREAD

**Issue by markgenest** [Elkfox/Ajaxinate#25]
Hi,

I am trying to use endless click to load blog articles that have a jquery slider on document load. However, when I append new content using the endless click, the ajax call breaks the jquery sliders on the new content completely. I've tried to understand how to use a callback functions to reload the scripts, but am having no luck in reloading them. 

I've wrapped all the functions tied to the slider into one function so I can call that function in the callback:

```
$(document).ready(function($) {

  function blogSlider() {
    $('.slider-pro').sliderPro({
       // options here...
    });
    // Another slider function here
    // Another slider function here
    // etc...
  }

  blogSlider();
});
```
I've tried to call the `function blogSlider()` when initializing ajaxify but don't know the correct syntax or if there is a better method of callback than the one mentioned in the [documentation](https://elkfox.github.io/Ajaxinate/#settings):

```
document.addEventListener("DOMContentLoaded", function() {
  var endlessClick = new Ajaxinate({
    method: 'click',
    loadingText: 'Loading...',
    callback: // DON'T KNOW THE SYNTAX HERE OR IF BETTER WAY TO CALL THE `blogSlider()` FUNCTION
  });
});
```
I even looked at this [callback issue posted here](https://github.com/Elkfox/Ajaxinate/pull/17), but am not sure how to make it work for my needs.

I'll qualify this all by saying I don't have much experience in jquery or ajax, so I'm not sure if what I'm even trying to do will work. Any help would be kindly appreciated! 

Thanks so much!
Mark

**Comment by ButsAndCats** [comment]
Try this @markgenest 
```
  var blogSlider = function blogSlider() {
    $('.slider-pro').sliderPro({
       // options here...
    });
    // Another slider function here
    // Another slider function here
    // etc...
  }

document.addEventListener("DOMContentLoaded", function() {
  var endlessClick = new Ajaxinate({
    method: 'click'
    loadingText: 'Loading...',
    callback: blogSlider
  });
});
```

**Comment by markgenest** [comment]
Yes that seemed to work. Thanks!
