### ISSUE TITLE
In Safari this.nextPageLinkElement is null not undefined

### ISSUE THREAD

**Issue by willhuang85** [Elkfox/Ajaxinate#28]
https://github.com/Elkfox/Ajaxinate/blob/a67e0530981e4f6319b92de19811262c94349f4f/src/ajaxinate.js#L76

At the line above, in Safari, the `this.nextPageLinkElement` is `null` not undefined.

Have not tried other browsers.

According to https://developer.mozilla.org/en-US/docs/Web/API/Document/querySelector, it'll return `null` if not found

**Comment by Cam** [comment]
@willhuang85 I see what you mean. I'll update to suit.

Thanks for reporting!

**Comment by Cam** [comment]
Oops. Looks like I submitted this fix prematurely. The issue still exists >.<

**Comment by Cam** [comment]
Fixed in 🔖 version: 2.0.10 [patch]
