### ISSUE TITLE
How to 'save' loaded products?

### ISSUE THREAD

**Issue by orby32** [Elkfox/Ajaxinate#29]
Let's say I've loaded products and enter to some of them, when I go beck to collection page the loaded products are gone and I need to browse them again. There is a way to save the loaded more products?

**Comment by Cam** [comment]
Yes, sort of. This is one of the biggest problems with the whole Ajax pagination concept really.

We've used a few methods. One was to cache all of the product data (and viewing position) in local storage. That worked quite well, but obviously encourages up a few potential headaches.

I'll close this out for now, as it isn't really an "issue". But please feel free to comment further and keep the discussion going. This is something we may well add support for at some point.
