### ISSUE TITLE
Occasional Can't find variable: Ajaxinate error

### ISSUE THREAD

**Issue by jonXmack** [Elkfox/Ajaxinate#32]
In both Chrome 71.0.3578.98 and Safari 12.0.1 on macOS 10.14.1 I'm getting an occasional `[Error] ReferenceError: Can't find variable: Ajaxinate`. I'm finding this is only after I have made changes to a template and I assume a cache is being cleared, after refreshing the page it's fine again. I've put in a workaround  to wait until Ajaxinate is loaded to set the `endlessScroll` variable, but thought I'd bring the issue up anyway.

**Comment by Cam** [comment]
That looks to me like the plugin in being called before it is loaded. You might need to load the plugin earlier on in the page.
