### ISSUE TITLE
Ajaxinate page says to use ID but code uses Class

### ISSUE THREAD

**Issue by prodikl** [Elkfox/Ajaxinate#36]
Had to look around in the source code since following the get started page: https://elkfox.github.io/Ajaxinate/ didn't work. 

The get started page says to use id="AjaxinateLoop" when in fact, the code uses class="AjaxinateLoop"

**Comment by mattmagi** [comment]
I was going to post this too, it drove me for a loop!

**Comment by Cam** [comment]
I've been meaning to rewrite the docs. Thanks for bringing this up. I'll make sure we update it soon.

**Comment by stanleynguyen** [comment]
@Cam as per our discussion in #42, I will rework the implementation to be using ID instead of class. Shall this ticket be changed to enhancement?
