### ISSUE TITLE
Issue with Ajax add to cart

### ISSUE THREAD

**Issue by iamitrovics** [Elkfox/Ajaxinate#40]
Hi,
i am having issues by using this plugin along with ajaxify-cart (adding to cart via ajax). If you check this link https://meetscarlet.myshopify.com/collections/pads first 12 items works just fine (add to cart via ajax, toggle button state etc). But when i scroll down and more items are loaded , those new items discard add to cart via ajax. If i click of any new loaded products page is reloaded. Thanks!

**Comment by brandonbrown** [comment]
This may just be a targeting issue. With dynamic data being added, the DOM may not become aware of the new elements. Target the document or a parent of the dynamically added element, and reach down from there. For example, with jquery:

`$(document).on('click', '.add-to-cart', function() {  ...  })`

**Comment by Cam** [comment]
Looks like you got this working. Thanks @brandonbrown 👍
