### ISSUE TITLE
Failed to set the 'responseType' property on 'XMLHttpRequest'

### ISSUE THREAD

**Issue by mateuspv** [Elkfox/Ajaxinate#43]
Hi, I just setup Ajaxinate on `blog.articles` collection, I got a `XMLHttpRequest` request error:

Failed to set the 'responseType' property on 'XMLHttpRequest': The response type cannot be changed for synchronous requests made from a document.

Throw by line: https://github.com/Elkfox/Ajaxinate/blob/master/src/ajaxinate.js#L120

![Screenshot from 2019-07-26 11-43-56](https://user-images.githubusercontent.com/4995440/61960023-10e8e180-af9b-11e9-9378-4b1374f44b9f.png)

```html
{% paginate blog.articles by 3 %}
    <div id="AjaxinateLoop" >
      {% for article in blog.articles %}
        {{ article.title }}
      {% endfor %}
    </div>

    <div id="AjaxinatePagination">
      {% if paginate.next %}
        <a href="{{ paginate.next.url }}">Loading More</a>
      {% endif %}
    </div>
{% endpaginate %}

```

```js
new Ajaxinate({
  container: '#AjaxinateLoop',
  pagination: '#AjaxinatePagination'
});
```

**Comment by Cam** [comment]
@mateuspv that suggest the request is being sent with a synchronous flag set. Ajaxinate doesn't set that flag, so this seems very odd to me.

Do you have a link to the project somewhere where I can view this happening? If not, the applicable part of the vendor.js file could help.

**Comment by wshen001** [comment]
@Cam  we do have the theme currently facing the same error. Therefore, I suggest re-open the ticket. 
I can share with you our theme preview link to produce the problem.

**Comment by marslan2037** [comment]
What happened to this ticket? i am also facing the same issue. Anyone, please help

**Comment by wshen001** [comment]
@marslan2037 the temporary hotfix we applied is to update the code directly to the library, you can follow the same implementation like https://github.com/Elkfox/Ajaxinate/pull/66 to your code directly.
