### ISSUE TITLE
Going back to collection from product page does not take you back to where you were.

### ISSUE THREAD

**Issue by BlockDigi** [Elkfox/Ajaxinate#46]
Hi,

This is my first ever GitHub comment - apologies if there are any mistakes or if I have done this wrong.

First of all - great plugin. We use it on a number of our sites and it seems to work very well.

That being said, one issue we've found is that clients are complaining that their customers are losing the point to which they scrolled too when they go from a collection page, to a product page, then back to a collection page. 

For example, a customer is scrolling down the page and pressed the "Load more" button 2 times. When they click a product and go back to collection, they're taken back to the top of the page.

Is there a way to go back to the point at which they left the collection page? 

Any help at all would be appreciated :)

**Comment by Cam** [comment]
@BlockDigi Congratulations! This is a good first issue, in that you explained your issue in a clear and respectful way 👍

What you are seeing is actually the intended default behaviour. As Shopify only loads a maximum of 50 products at a time, the additional products need to be fetched in batches after load. When you press the back button, the page is essentially reloading the first state of the page, with only the first set of products.

You could extend the library with your own functionality to support the kind of thing you are after.

Check out this comment for some ideas on how you could add this kind of functionality yourself https://github.com/Elkfox/Ajaxinate/issues/41#issuecomment-524524194

See also #33, #41
