### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by dsiosoft** [Elkfox/Ajaxinate#48]
https://bodtek.co/collections/mens

I have setup Ajax-pagination here. Now I want to set custom display limit here.
how can I display only first 8 product using this code.
currently it's display 9 product at first.

any one help.

 document.addEventListener("DOMContentLoaded", function() {
    var endlessClick = new Ajaxinate({
      method: 'click'
    });
  });

**Comment by Cam** [comment]
@dsiosoft Just change your pagination liquid tag. Ajaxinate inherits the pagination etc from the native liquid markup.

**Comment by dsiosoft** [comment]
I have set custom code for display each product variants on collection page instead of product.
If I set limit in liquid ( 1 ). then it's display all variant in 1 product.
Currently I have set Limit for 2.


{% if collection.handle == 'all' %}
{% assign limit = 999 %}
{% else %}
{% assign limit = 2 %}
{% endif %}

{% paginate collection.products by limit %}
{% paginate %}

![Colleciton page](https://user-images.githubusercontent.com/46180840/69841888-01e6a880-1287-11ea-8ba2-6a8f18afb413.PNG)

**Comment by Cam** [comment]
Then you would need to find a way to count variants in each product and use that when fetching the next set. You could do that with a bit of liquid and custom and javascript. Shouldn't be too hard.

That's a little outside the scope of the Ajaxinate project though, so I'll close this out.

**Comment by dsiosoft** [comment]
If you any Idea about find next set of variant then please share. because I am stuck with this.
Any reference. any logic ??

**Comment by Cam** [comment]
The {{ product.variants }} object has an array of the variants in each product, and the Ajax API has an array of the variants too https://help.shopify.com/en/themes/development/getting-started/using-ajax-api#get-product
