### ISSUE TITLE
Products being duplicated 

### ISSUE THREAD

**Issue by untetheredcollective** [Elkfox/Ajaxinate#53]
If I set the pagination for less products than there are in the collection, all products are loaded upon scroll plus additional duplicated products. For example, I set the pagination to 24 and there are 27 products in the collection. It loads the 27 plus 3 duplicate products of the last 3 products of the 27. I would expect it to load the 27 products and stop there. Happens on desktop/mobile and all browsers. 

Screenshot: http://prntscr.com/rasjnc

**Comment by Cam** [comment]
@untetheredcollective Hmm, interesting. I haven't seen that behaviour before.

Can you upload to a dev store so I can take a look? A fix will be pretty easy, once we confirm.
