### ISSUE TITLE
problem for duplicate product in debut theme

### ISSUE THREAD

**Issue by mchmddiazz** [Elkfox/Ajaxinate#57]
Hi @Cam can you help me? I got the duplicate product when I'm trying slow scrolling. Am I wrong in the coding section or is there one of the parts that I haven't entered?
![Screenshot_141](https://user-images.githubusercontent.com/32628733/87402614-07aab780-c5e6-11ea-8e3c-e79572acf547.png)
![Screenshot_142](https://user-images.githubusercontent.com/32628733/87402617-0a0d1180-c5e6-11ea-8039-3165c58eb16d.png)

nonarara.myshopify.com
password: nonarara

**Comment by Cam** [comment]
Hi @mchmddiazz. Looks like you already resolved this. Is that correct?
