### ISSUE TITLE
Non-Infinite?

### ISSUE THREAD

**Issue by HotpotCreative** [Elkfox/Ajaxinate#58]
Hi @Elkfox.

Great plugin. Works quick and a treat.

My client is wondering if the plugin can be 'non-infinite'. As in, once it reaches the end of a collection, it stops.
I wasn't able to work out anything by looking at the docs or code, but I'm usually a front-end Dev (ahh, my shame!).

**Comment by Cam** [comment]
@HotpotCreative Thanks!

You could use the destroy method to stop it at any point you choose. But I'm not sure I'm totally understanding your question. There shouldn't be any more items loading after all of the items in the collection have loaded.

**Comment by HotpotCreative** [comment]
> There shouldn't be any more items loading after all of the items in the collection have loaded.

It's looping continuously through all products in that collection when reaching the end.

https://huxbaby-launch.myshopify.com/collections/wilderness (Access PW is 'fentai')

**Comment by Cam** [comment]
Can you please paste the logic for your pagination element here (and surrounding lines). I suspect that's where the issue must be, but obviously can't see liquid via inspector.

**Comment by HotpotCreative** [comment]
**Main collection loop:**

`
{% for product in collection.products %}
            	  {% if product.available %}
                  < div class="col-6 col-md-4 mx-0 entry px-0" >

                    {% assign label = "" %}
                    {% assign sus = "" %}
                    {% assign feature_collection = settings.current_season_collection %}
                    {% if product.available %}
                      {% for c in product.collections %}
                        {% if c.handle == feature_collection %}
                            {% assign label = "new" %}
                        {% endif %}
                        {% comment %} The below 'sale' overrides the above 'best seller' since being on sale is more important {% endcomment %}
                        {% if c.handle == "sale" %}
                            {% assign label_sale = "sale" %}
                        {% endif %}
                    	{% if c.handle == "sustainable" or c.handle == "organic" %}
                            {% assign sus = "yes" %}
                        {% endif %}
                      {% endfor %}
                    {% else %}
                    	{% assign label = "sold out"%}
                    {% endif %}
                    
                    <a class="d-block text-center bg-white product" href="{{ product.url }}">
                      {% if label != "" or label_sale != "" %}
                      	<div class="mr-auto sticker {% if label_sale == "sale" %}sale{% endif %}">{% if label_sale != "sale" %}New{% else %}Sale{% endif %}</div>
                      {% endif %}
                      
                      
                      {% assign product = all_products[block.settings.product] %}
                      <div class="figure w-100 swap" style="{% if product.available %}background-image: url('{{ product.images[1] | img_url: '1400x' }}');{%else%}opacity: .25;{%endif%}">
                        <div class="mr-auto sticker-sustainable {% if label_sale == "sale" or label == "new"%}bump{%else%}mt-1{% endif %}">
                          {% for tag in product.tags %}
                              {% if tag == "sustainable" %}{% if forloop.first == true %}{%else%}{%endif%}Sustainable<br />{% endif %}
                              {% if tag == "organic" %}{% if forloop.first == true %}{%else%}{%endif%}Organic Cotton<br />{% endif %}
                              {% if tag == "recycled" %}{% if forloop.first == true %}{%else%}{%endif%}Recycled polyester<br />{% endif %}
                              {% if tag == "spf50" %}{% if forloop.first == true %}{%else%}{%endif%}SPF 50+<br />{% endif %}
                              {% if tag == "reversible" %}{% if forloop.first == true %}{%else%}{%endif%}Reversible<br />{% endif %}
                          {% endfor %}
                        </div>
                        <img src="{{ product.featured_image | img_url: '1400x'}}" alt="Huxbaby - {{ product.title }}" class="img-fluid">
                      </div>
                      <div class="info">
                        <span class="title d-block">{{ product.title }}</span>
                        {% if sus == "yes" %}
                        <div class="d-block d-lg-none" style="font-size: 12px;">
                          {% for tag in product.tags %}
                          	{% if tag == "organic" %}{% if forloop.first == true %}{%else%}{%endif%}+ Organic Cotton<br />{% endif %}
                            {% if tag == "recycled" %}{% if forloop.first == true %}{%else%}{%endif%}+ Recycled polyester<br />{% endif %}
                            {% if tag == "spf50" %}{% if forloop.first == true %}{%else%}{%endif%}+ SPF 50+<br />{% endif %}
                            {% if tag == "reversible" %}{% if forloop.first == true %}{%else%}{%endif%}+ Reversible<br />{% endif %}
                          {% endfor %}
                      	</div>
                        {% endif %}
                      	<span class="price d-block">{{ product.price | money_with_currency }}</span>
                        
                      </div>
                      
                    </a>

                  </div>
            	  {% endif %}

              {% endfor %}
`

**Below collection loop:**
`{% if paginate.pages > 1 %}
  <div class="container-fluid text-center" id="collection-paginate">
    < a href="{{ paginate.next.url }}" class="btn btn-outline-primary nohover">Load More</a >
  </div>
{% endif %}
`


**At bottom of collection page:**
`<script>
  document.addEventListener("DOMContentLoaded", function() {
    var endlessScroll = new Ajaxinate({
      container: '#collection-loop',
      pagination: '#collection-paginate',
      method: 'click'
    });
  });
</script>`

**Comment by Cam** [comment]
@HotpotCreative You should just need to change `{% if paginate.pages > 1 %}` to `{% if paginate.next %}`.
