### ISSUE TITLE
Gulp error: Unexpected token: keyword «const»

### ISSUE THREAD

**Issue by ConduciveMammal** [Elkfox/Ajaxinate#59]
**Describe the bug**
I'm trying to use the NPM package along with Gulp-Uglify but the Ajaxinate package is causing a compile error:

```
 GulpUglifyError: unable to minify JavaScript
Caused by: SyntaxError: Unexpected token: keyword «const»
```
If I remove `import { Ajaxinate } from 'ajaxinate';` from the top of my file, it compiles fine.

**Comment by Cam** [comment]
@ConduciveMammal It looks like UglifyJS doesn't support ES6 syntax, which Ajaxinate uses. Take a look at [this Stack Exchange post for some options](https://stackoverflow.com/questions/47439067/uglifyjs-throws-unexpected-token-keyword-const-with-node-modules).
