### ISSUE TITLE
Images not loading

### ISSUE THREAD

**Issue by monsmedia** [Elkfox/Ajaxinate#62]
Hello, I have a custom theme and was able to implement Ajaxinate. 
However when I click on the load more button, it loads the other products but not the images. 

![images_not_loading](https://user-images.githubusercontent.com/34288228/94750610-0e76da00-034c-11eb-8faa-5707cd01f9f6.gif)
-- edit -- 
On further inspection it seems that it does not load the image in `src` and instead loads the default image. It is correctly being loaded in `data-src`

`<img class="card-img-top" src="//cdn.shopify.com/default-image.jpg" data-src="//cdn.shopify.com/woolfill-jacket.jpg" alt="Duckworth Woolfill Jacket" width="250" height="250" loading="lazy">`

I must be doing something wrong in the liquid template:
`        <img
          class="card-img-top"
          src="{{ 'default-image.jpg' | asset_img_url: image_size, crop: 'center' }}"
          data-src="{{ product.featured_image | img_url: image_size, crop: 'center'  }}"
          alt="{{ product.featured_image.alt | escape }}"
          width="{{ section.settings.image_width }}"
          height="{{ section.settings.image_height }}"
          loading="lazy"
        >`

**Comment by Cam** [comment]
@monsmedia Your theme is using some form of lazy loading for those images. So you'll need to wire up the callback to re-initialise the lazy loading when new images are loaded.

You could also just change `default-image.jpg'` to `product.featured_image`.

**Comment by lightmar** [comment]
Hi, I'm facing the same problem.
@monsmedia did you find a solution for that?
@Cam How can you re-initialise the lazy loading?
Thank you!
