### ISSUE TITLE
Dynamic number of products/items to load

### ISSUE THREAD

**Issue by shaniadicen** [Elkfox/Ajaxinate#63]
I am building a Shopify collections page and would like to a way to change the number of products to load when the user clicks on the button. It looks like for now, there is no option to do this and that the number of products that will load will always be the same to the initial products that displayed on page load.

I would like there to be a way for the number of products to load to be dynamic or changeable.

I tried to use a dynamic product count for paginate but it looks like it doesn't work.

Does anyone know a way around this or how to make this work?

**Comment by Cam** [comment]
@shaniadicen this isn't possible due to the way Shopify pagination works.
