### ISSUE TITLE
Lazy loading issue

### ISSUE THREAD

**Issue by lightmar** [Elkfox/Ajaxinate#68]
Hi,
My theme uses lazy loading to load the images on the collection pages, so when a new page is being loaded using Ajaxinate, the images doesn't show.
How is it possible to activate the lazy loading on the new items that are being loaded using Ajaxinate?
I use the Impulse theme.

Thank you!

**Comment by Cam** [comment]
Hey @lightmar. You need to use the callback to initiate lazy loading on new items as they are added.
