### ISSUE TITLE
Any way to slow the loading down so we can see the text for a specific period of time?

### ISSUE THREAD

**Issue by joshuahalldesign** [Elkfox/Ajaxinate#70]
I have a client who is wanting the ajaxinate load to be slower (i know.. illogical hey!) so they read the loadingText.

Example. When scroll down, the loadingtext appears for 3s and then fades out revealing the new posts after that...

**Comment by Cam** [comment]
Hi @joshuahalldesign. I think the easiest way would be to create a fork of the project and add a delay. I can't think of any practical way to do this using the library as it works currently.

You could use the endless click method and trigger a click yourself. But that doesn't seem all that elegant.
