### ISSUE TITLE
Endless scroll doesn't work on the demo page

### ISSUE THREAD

**Issue by tomaszbujnowicz** [Elkfox/Ajaxinate#71]
**Describe the bug**
The endless scroll feature doesn't work anymore - on the demo page

**To Reproduce**
1. Go to the demo page https://ajaxinate.myshopify.com/collections/all
2. Scroll down
3. See error, products are not loaded and "Loading More Products" message is hanging

It's only the scroll method, click works properly.

**Comment by Cam** [comment]
Hey @tomaszbujnowicz. It still works. You can see the demo at https://ajaxinate.myshopify.com (root URL).

Thanks for alerting me to the collocations all page though. I'll update the demo to show endless scroll on all collection pages except the endless click demo.

**Comment by tomaszbujnowicz** [comment]
Thanks @Cam for a quick reaction here 🙌
Closing the ticket since it has been resolved.
