### ISSUE TITLE
Loading... remains constant

### ISSUE THREAD

**Issue by harshlohana** [Elkfox/Ajaxinate#72]
After all products are loaded successfully , loading text still remains in my collection page.
Attached the console errors as ss please look into it.
Theme - empire.js
link - https://lightingdesign.com/collections/portable-and-wall
![Screenshot 2021-07-09 155250](https://user-images.githubusercontent.com/47289608/125105207-da5eef80-e0fb-11eb-8531-84addef9c883.png)

**Comment by cam** [comment]
Hi. It's hard to tell without seeing the liquid markup. But it looks to me like your pagination isn't set up correctly.

**Comment by harshlohana** [comment]
`

<script
  type="application/json"
  data-section-type="static-collection"
  data-section-id="{{ section.id }}"
  data-section-data
>
  {
    "context": {
      "see_more": {{ 'general.general.see_more' | t | json }},
      "see_less": {{ 'general.general.see_less' | t | json }},
      "grid_list": {{ section.settings.default_view | json }},
      "collectionUrl": {{ collection.url | default: '/collections/all' | json }}
    }
  }
</script>

{% assign show_sidebar = true %}
{% assign show_filters = true %}
{% assign show_filter_trigger = false %}

{% if section.settings.filter_style == 'none' %}
  {% assign show_filters = false %}
{% endif %}

{% if section.settings.show_sidebar %}
  {% comment %}
    Sidebar toggle is used on mobile only, and will only show Filters
  {% endcomment %}

  {% if collection.all_tags.size > 0 and show_filters %}
    {% assign show_filter_trigger = true %}
  {% endif %}

  {% if section.blocks.size > 0 or collection.all_tags.size > 0 and show_filters %}
    {% comment %}
      Sidebar to show only if there are tags in the collection, or there are menus
    {% endcomment %}
    {% assign show_sidebar = true %}
  {% endif %}
{% endif %}

{% assign paginate_by = section.settings.products_per_page_range %}
{% if template contains 'view-24' %}
  {% assign paginate_by = 24 %}
{% elsif template contains 'view-36' %}
  {% assign paginate_by = 36 %}
{% elsif template contains 'view-48' %}
  {% assign paginate_by = 48 %}
{% endif %}

{%- capture collection_classes -%}
  {% if show_sidebar %}
    layout--has-sidebar
  {% else %}
    layout--no-sidebar
  {% endif %}

  {% if section.settings.default_view == 'grid-view' %}
    productgrid-gridview
  {% else %}
    productgrid-listview
  {% endif %}
{%- endcapture -%}

{% render 'breadcrumbs' %}


{% style %}
div.utils-view-container{
	display: none;
}
@media only screen and (min-width: 768px){
    .collection--description {
      max-width: 600px;
      margin: 0 auto;

    }

    .collection--description {
        padding: 70px 0 45px;
    }



{% endstyle %}


{% paginate collection.products by paginate_by %}
  <div class="productgrid--outer {{ collection_classes | strip_newlines }}">
    <div class="productgrid--masthead">
	{% comment %}
      {% if section.settings.show_collection_image and collection.image %}
        <figure class="collection--image">
          {%
            render 'rimg',
            img: collection.image,
            size: '1350x',
            lazy: false,
            canvas: true
          %}
        </figure>
      {% endif %}
     {% endcomment %}
      {% if section.settings.show_collection_image and collection.image %}
      
        {% for link in linklists.collection-logic-menu.links %}
          {% if link.url == collection.url %}
            {% style %}
                .collection-hero {
                  background-image: url({{ collection.image.src | collection_img_url: 'original' }});
                  background-size: cover;
                  background-repeat: no-repeat;
                    padding: 8px 0;
                }

                @media only screen and (min-width: 768px){
                  .collection-hero {
                    padding: 75px 0;
                  }      
                }

                  .collection-hero > h1 {
                        margin: 0;
                      color: #fff !important;
                      text-align: center;
                  }
            {% endstyle %}
          {% endif %}
        {% endfor %}




      

		<div class="collection-hero">
          <h1 class="collection--title">
            {{ collection.title }}
          </h1>
      	</div>
      {% else %} 
          <h1 class="collection--title">
            {{ collection.title }}
          </h1>
      {% endif %}

      {% if collection.description != blank %}
        <div class="collection--description rte">
          {{ collection.description }}
        </div>
      {% endif %}
      
      <div class="subcategory-section">
      	{% render 'subcategory-section' %}
      </div>
    </div>


    
    {% if show_sidebar %}

	{% comment %}
      {%
        render 'product-grid-sidebar',
        filter_style: section.settings.filter_style,
        filter_position: section.settings.filter_position,
        filter_limit: section.settings.filter_limit,
        menu_depth: section.settings.menu_depth_range,
        show_prod_count: section.settings.show_prod_count
      %}
    {% endcomment %}

    	{% render 
         'custom-sidebar-filters' 
    	%}
    {% endif %}
    <div class="productgrid--wrapper">

      {% if show_filter_trigger or section.settings.sort_by or section.settings.show_by or section.settings.grid_list %}
        {% capture utility_class %}
          productgrid--utils

          {% if show_filter_trigger or section.settings.sort_by or section.settings.grid_list %}
            productgrid--utils--visible-mobile
          {% endif %}

          {% unless section.settings.show_by or section.settings.sort_by or section.settings.grid_list %}
            productgrid--utils--hidden-desktop
          {% endunless %}
        {% endcapture %}
        <nav
          class="{{ utility_class | strip_newlines }}"
          aria-label="{{ 'general.accessibility.nav_collection_utilities' | t }}"
        >
          {% if show_filter_trigger %}
            {%- assign filter_count = 0 -%}
            {%- if current_tags.size > 0 -%}
              {%- assign filter_count = current_tags.size -%}
            {%- endif -%}
            <div class="productgrid--utils utils-filter">
              <button
                class="utils-filter-button"
                type="button"
                aria-label="{{ 'product_grid.filters.title_count' | t: count: filter_count }}"
                data-productgrid-trigger-filters
              >
                <span class="utils-filter-icon">
                  {%- render 'icon-filters' -%}
                </span>
                <span class="utils-filter-text">
                  {{- 'product_grid.filters.title_count' | t: count: filter_count -}}
                </span>
              </button>
            </div>
          {% endif %}

          {%- if section.settings.sort_by -%}
            {%-
              render 'product-grid-sortby',
              type: 'select',
            -%}
          {%- endif -%}

          {%- if section.settings.show_by or section.settings.grid_list -%}
            <div
              class="
                productgrid--utils
                utils-view
                {% if section.settings.grid_list == false %}
                  utils-hide
                {% endif %}
              "
            >
              <div class="utils-view-container">
                {%- if section.settings.show_by -%}
                  {%-
                    render 'product-grid-showby',
                    show_by: paginate_by,
                  -%}
                {%- endif -%}

                {% if section.settings.grid_list %}
                  <div class="utils-viewtoggle">
                    <span class="utils-viewtoggle-label">
                      {{ 'product_grid.view_as.title' | t }}
                    </span>

                    <button
                      class="utils-viewtoggle-button {% if section.settings.default_view == 'grid-view' %}active{% endif %}"
                      data-collection-view="grid-view"
                      aria-label="grid view"
                    >
                      {% render 'icon-library', id: 'icon-grid' %}
                    </button>

                    <button
                      class="utils-viewtoggle-button {% if section.settings.default_view == 'list-view' %}active{% endif %}"
                      data-collection-view="list-view"
                      aria-label="list view"
                    >
                      {% render 'icon-library', id: 'icon-list' %}
                    </button>
                  </div>
                {% endif %}
              </div>
            </div>
          {%- endif -%}
        </nav>
      {% endif %}
      {% if current_tags.size > 0 %}
        <div class="productgrid--filters">
          {%- render 'product-grid-tags-active' %}
        </div>
      {% endif %}

      {% if collection.products.size > 0 %}
        <ul id="AjaxinateContainer" class="productgrid--items products-per-row-{{- section.settings.products_per_row -}}">
       
          {% for product in collection.products %}
            {%
              render 'product-grid-item2',
              product: product
            %}
          {% endfor %}
         
        </ul>
      {% else %}
        <div class="productgrid--no-results">
          <h2 class="productgrid--no-results-title">
            {%- if collection.all_products_count == 0 -%}
              {{ 'product_grid.no_results.empty' | t }}
            {%- else -%}
              {{ 'product_grid.no_results.tags_empty' | t }}
            {%- endif -%}
          </h2>

          <a class="productgrid--no-results-button" href="{{ routes.all_products_collection_url }}">
            {{ 'search.general.view_all_products' | t }}
          </a>
        </div>
      {% endif %}
		
      
      {%
        render 'pagination2', paginate: paginate,
        grid_list: true
      %}
     
    </div>
  </div>
{% endpaginate %}



{% assign grid_list = grid_list | default: nil %}


{% if paginate.previous or paginate.next %}
  <nav class="pagination--container" aria-label="Pagination">
    <ul class="pagination--inner">

      {% if paginate.previous %}
        <li style="visibility:hidden;" class="pagination--previous">
          <a
            class="pagination--item"
            href="{{- paginate.previous.url -}}{%- if grid_list -%}&grid_list{%- endif -%}"
            aria-label="Go to previous page"
          >
            <span class="pagination--chevron-left" aria-hidden="true">
              {% render 'icon-chevron-down-small' %}
            </span>

            {{ 'general.pagination.prev' | t }}
          </a>
        </li>
      {% endif %}


      {% for part in paginate.parts %}
        {% if part.is_link %}
          <li style="visibility:hidden;">
            <a
              class="pagination--item"
              href="{{ part.url }}{% if grid_list %}&grid_list{% endif %}"
              aria-label="Go to page {{ part.title }}"
            >
              {{ part.title }}
            </a>
          </li>
        {% else %}
          {% if part.title == '&hellip;' %}
            <li style="visibility:hidden;" class="pagination--ellipsis">
              <span class="pagination--item">
                {{ part.title }}
              </span>
            </li>
          {% else %}
            <li style="visibility:hidden;"
              class="pagination--active"
              aria-label="Page {{ part.title }}"
              aria-current="true"
            >
              <span class="pagination--item">
                {{ part.title }}
              </span>
            </li>
          {% endif %}
        {% endif %}
      {% endfor %}
      
     <div>
      {% if paginate.next %}
    
        <li id="AjaxinatePagination"  class="pagination--next">
      
          <a
            class="pagination--item"
            href="{{- paginate.next.url -}}{%- if grid_list -%}&grid_list{%- endif -%}"
            aria-label="Go to next page"
          >
            {{ 'general.pagination.next' | t }}
            <span class="pagination--chevron-right" aria-hidden="true">
              {% render 'icon-chevron-down-small' %}
            </span>
          </a>
          
        </li>
      {% endif %}
      
    </ul>
  </nav>
{% endif %}
`

**Comment by harshlohana** [comment]
@Cam i have attached the code please help me with it

**Comment by cam** [comment]
@harshlohana If you can share the the original file I can take a look. The pasted version is pretty messed up.

**Comment by harshlohana** [comment]
[paginate2.liquid.txt](https://github.com/Elkfox/Ajaxinate/files/6799338/paginate2.liquid.txt)
[collection.liquid.txt](https://github.com/Elkfox/Ajaxinate/files/6799339/collection.liquid.txt)

@Cam yes sure, these are the files

**Comment by cam** [comment]
@harshlohana can you please try moving the pagination ID to the top element of your pagination structure. It should be adjacent to the paginated content container.
