### ISSUE TITLE
Fails when products are sorted

### ISSUE THREAD

**Issue by mortenladefoged** [Elkfox/Ajaxinate#74]
Hi,
I'm building a Shopify store and have implemented the endless scroll Ajaxinate on my collection template and it works great.

However if I sort my products, let says price ascending, and hit the load more products, I end up with this URL

https://lavinordic.dk/collections/bolig-og-interior?page=2&sort_by=price-ascending&view=ajax

resulting in all links to images, stylesheets etc are broken.

Any idea on how to fix that?

![image](https://user-images.githubusercontent.com/88491072/128344851-5afd0497-fa66-43d7-ad5f-d05608970258.png)

**Comment by cam** [comment]
Hi @mortenladefoged. Can you grant me access the frontend of your dev store to take a look?

**Comment by mortenladefoged** [comment]
Hi @Cam. No problem. Which email should I send the invite to?

**Comment by cam** [comment]
Please send the frontend preview password to issue-961741107@elkfox.com

**Comment by mortenladefoged** [comment]
Access to frontend preview sent

**Comment by cam** [comment]
Thanks Morten. I had a look at the issue, and it seems to be due to the fact the collection is actually loaded from a different source when you change the sorting. The theme is fetching new contents from the `collection.ajax.liquid` template.

At a guess I would say that you need to update the collection.ajax template to suit the plugin too.

**Comment by mortenladefoged** [comment]
![image](https://user-images.githubusercontent.com/88491072/128669711-9f3b85cd-be20-410a-b319-d83c303e50ff.png)
![image](https://user-images.githubusercontent.com/88491072/128669726-ce2e73ce-c87b-412f-8f85-c6884a3bb8ef.png)
Hi Cam. Thanks for your reply. I'm not quite sure on how to update the ajax collection file, besides calling the js on this as well. They both use the same colletion-template section.

**Comment by cam** [comment]
@mortenladefoged You probably need to add the listener again when the page is reloaded dynamically. Alternatively you could disable the ajax sorting option, so the page reloads fully when the sorting method is changed.

I'll close this for now, as it isn't an issue with the plugin itself.
