### ISSUE TITLE
page state not reserved for the loaded cards

### ISSUE THREAD

**Issue by testt1048** [Elkfox/Ajaxinate#86]
It's on a new bought theme called Tailor and we're having a bit of an issue with infinite scroll: Basically we're finding on some desktop devices that when a user scrolls down a collection page, then into a product, and then uses the 'back' button or browses to another page, the scroll position gets confused. Users sometimes get stuck at the bottom of the page, or the page flickers and jumps around a bit before taking you back to your original position.

you can see the issue on this page : https://www.seolgold.com/collections/earrings
Kindly please help asap.

**Comment by cam** [comment]
Hi. This looks like the same issue as #83. Please check out the thread for that issue.
